AWSTemplateFormatVersion: "2010-09-09"
Description: Tailscale Exit Node on Lightsail with Static IP (Ubuntu 24.04)

Parameters:
  TailscaleAuthKey:
    Type: String
    NoEcho: true
    Description: Tailscale auth key (starts with tskey-...)

Resources:
  TailscaleNode: 
    Type: AWS::Lightsail::Instance
    Properties:
      BlueprintId: ubuntu_24_04
      BundleId: nano_2_0
      InstanceName: TailScaleExitNode
      Networking: 
        Ports:
          - AccessDirection: inbound
            AccessFrom: "Anywhere (0.0.0.0/0)"
            AccessType: Public
            Protocol: udp
            FromPort: 41641
            ToPort: 41641
      UserData: 
        !Sub |
          #!/bin/bash -xe

          # Enable IP forwarding
          echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.conf
          echo 'net.ipv6.conf.all.forwarding = 1' >> /etc/sysctl.conf
          sysctl -p /etc/sysctl.conf

          # Install Tailscale
          curl -fsSL https://tailscale.com/install.sh | sh

          # Start tailscaled
          systemctl enable --now tailscaled
          sleep 5

          # Tailscale up
          tailscale up --advertise-exit-node \
            --hostname=lightsail-exit-node \
            --authkey ${TailscaleAuthKey}

  TailscaleStaticIp:
    Type: AWS::Lightsail::StaticIp
    Properties:
      StaticIpName: TailscaleStaticIp

Outputs:
  InstanceName:
    Description: Name of the Tailscale node
    Value: !Ref TailscaleNode

  StaticIpName:
    Description: Name of the static IP
    Value: !Ref TailscaleStaticIp

  StaticIpAddress:
    Description: Public static IP address
    Value: !GetAtt TailscaleStaticIp.IpAddress
